server:
  port: 8080

spring:
  flyway:
    enabled: true
  datasource:
    url: "jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_NAME:demo-db}"
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

security:
  allowed-origin-urls: "${ALLOWED_ORIGIN_URLS:http://localhost:3000}"
